import downloadGitRepo from './utils/download';
import readJson from './utils/read-json';
import traverse from './utils/traverse';
import {
  parseScaffoldName,
  parseExtendScaffoldName,
  checkConflictBlockCount,
  solveConflicts,
  parseRepoDescription,
  parseFilePathname,
  isPathnameInConfig,
} from './utils/scaffold';
import {
  getComposedArrayValue,
  getExtendedPropsFromParentScaffold,
} from './utils/generator';
import { parseComposeConfig, stringifyComposeConfig } from './utils/compose';
import { diff, merge, checkFileAction, stringifyBlocks, parseDiff, parseFileContent } from './utils/diff';
import DollieInteractiveGenerator from './generators/interactive';
import DollieComposeGenerator from './generators/compose';
import dollie, { runContainer, runWeb } from './api';
import {
  DiffChange,
  PatchTableItem,
  PatchTable,
  CacheTable,
  ConflictSolveItem,
  ConflictSolveTable,
  TraverseResultItem,
  DollieScaffold,
  DollieScaffoldProps,
  DollieScaffoldConfiguration,
  DollieScaffoldNameParser,
  FileAction,
  MergeResult,
  MergeBlock,
  Conflict,
  ComposedConflictKeepsTable,
} from './interfaces';
import {
  APP_NAME,
  HOME_DIR,
  CACHE_DIR,
  TEMP_DIR,
  TRAVERSE_IGNORE_REGEXP,
  APP_SCAFFOLD_PREFIX,
  APP_EXTEND_SCAFFOLD_PREFIX,
  APP_SCAFFOLD_DEFAULT_OWNER,
  APP_COMPOSE_CONFIG_MAP,
} from './constants';

export {
  // functions
  downloadGitRepo,
  readJson,
  traverse,
  parseScaffoldName,
  parseExtendScaffoldName,
  getComposedArrayValue,
  getExtendedPropsFromParentScaffold,
  parseComposeConfig,
  stringifyComposeConfig,
  diff,
  merge,
  checkFileAction,
  stringifyBlocks,
  checkConflictBlockCount,
  solveConflicts,
  parseDiff,
  parseRepoDescription,
  parseFilePathname,
  isPathnameInConfig,
  parseFileContent,
  runContainer,
  runWeb,
  // objects
  dollie,
  // classes
  DollieInteractiveGenerator,
  DollieComposeGenerator,
  // interfaces and types
  DiffChange,
  PatchTableItem,
  PatchTable,
  CacheTable,
  ConflictSolveItem,
  ConflictSolveTable,
  TraverseResultItem,
  DollieScaffoldConfiguration,
  DollieScaffoldProps,
  DollieScaffold,
  DollieScaffoldNameParser,
  MergeResult,
  MergeBlock,
  Conflict,
  ComposedConflictKeepsTable,
  FileAction,
  // constants
  APP_NAME,
  HOME_DIR,
  CACHE_DIR,
  TEMP_DIR,
  TRAVERSE_IGNORE_REGEXP,
  APP_SCAFFOLD_PREFIX,
  APP_EXTEND_SCAFFOLD_PREFIX,
  APP_SCAFFOLD_DEFAULT_OWNER,
  APP_COMPOSE_CONFIG_MAP,
};

export default {
  downloadGitRepo,
  readJson,
  traverse,
  parseScaffoldName,
  parseExtendScaffoldName,
  getComposedArrayValue,
  getExtendedPropsFromParentScaffold,
  parseComposeConfig,
  stringifyComposeConfig,
  diff,
  merge,
  checkFileAction,
  stringifyBlocks,
  checkConflictBlockCount,
  solveConflicts,
  parseDiff,
  parseRepoDescription,
  parseFilePathname,
  isPathnameInConfig,
  parseFileContent,
  runContainer,
  runWeb,
  dollie,
  DollieInteractiveGenerator,
  DollieComposeGenerator,
  APP_NAME,
  HOME_DIR,
  CACHE_DIR,
  TEMP_DIR,
  TRAVERSE_IGNORE_REGEXP,
  APP_SCAFFOLD_PREFIX,
  APP_EXTEND_SCAFFOLD_PREFIX,
  APP_SCAFFOLD_DEFAULT_OWNER,
  APP_COMPOSE_CONFIG_MAP,
};
